version: '3'

services:
  php:
    build: .
    volumes: 
      - ./:/app
    working_dir: /app
    restart: always
    depends_on: 
      - mysql
    ports: 
      - 80:80
      - 443:443

  mysql:
    image: mysql:8
    restart: always
    environment: 
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 1